export const GET_INCREMENT_ID = 'GET_INCREMENT_ID';


export const ADD_SUBINPUT = 'ADD_SUBINPUT';
export const DELETE_SUBINPUT = 'DELETE_SUBINPUT';

export const CREATE_INPUT = 'CREATE_INPUT';
export const REMOVE_INPUT = 'REMOVE_INPUT';

export const CHANGE_INPUT_TYPE = 'CHANGE_INPUT_TYPE';
export const UPDATE_QUESTION_TEXT = 'UPDATE_QUESTION_TEXT';

export const CHANGE_CONDITION = 'CHANGE_CONDITION';

export const RESET_PREVIEW = 'RESET_PREVIEW';
export const LOAD_PREVIEW = 'LOAD_PREVIEW';
export const EVALUATE_INPUT_FOR_PREVIEW = 'EVALUATE_INPUT_FOR_PREVIEW';
